### ISSUE TITLE
Automate the release process

### ISSUE THREAD

**Issue by pradyunsg** [pypa/packaging#253]
I think we all agree that this would be a good idea.

We have a few options here IMO:

- Have a GitHub Action triggered on tag, that runs the release processes
  - 2 stage: bump+tag+bump+push (releaser), build+publish (automation)
  - Needs auth/API token management
  - Consistent build environment
- Add something like https://github.com/pradyunsg/vendoring/blob/master/noxfile.py#L103-L146
  - Runs on the *release manager*'s system
  - Performs exactly the same steps as a manual release process, except automatically.
- A combination of the two above?
  - version bumping + tagging + push is done by automation locally.
  - package building + publishing is done by CI automation.

Personally, I think doing 2, then 3 would be easiest -- partly because I am familiar with the second approach. :)

**Comment by brettcannon** [comment]
So the package building is already being done as part of the lint action, so that's easy enough to do.😉 And having twine do an upload with a scoped PyPI token should be very easy. I think it would be:
```yaml
# I'm assuming twine was already installed.
- name: Upload to PyPI
  env:
    TWINE_USERNAME: "__token__"
    TWINE_PASSWORD: "${{ secrets.PYPI_TOKEN }}"
  run: twine upload
```

I think the question is whether versioning needs to be automatic. And with a GitHub Action you can actually push that back in a git commit if you wanted it to be fully automated based on a tag.

And after that if you want to get fancy you can try and push the built artifacts to the release on GitHub (although I don't think it's worth the hassle).
